:h1 res=5400
x=right y=bottom
width=100%
height=100%
.Setup strings
:p.
The following setup strings are introduced by WPS-wizard.
:p.
:hp2.Objects:ehp2.
:table cols='20 15 40' rules=both frame=box.
:row.
:c.KEYNAME
:c.VALUE
:c.DESCRIPTION

:row.
:c.WIZSETREXXSCRIPT
:c.path
:c.Attach a REXX script to an object.
:p.
Example&colon.
:p.
:p.
WIZSETREXXSCRIPT=x&colon.\path\file.rx
:etable.

:p.
:hp2.Folders:ehp2.
:table cols='20 15 40' rules=both frame=box.
:row.
:c.KEYNAME
:c.VALUE
:c.DESCRIPTION

:row.
:c.WIZENABLEINFOWINDOW
:c.1/0
:c.Enable or disable the information area of a folder.
:p.
Example&colon.
:p.
:p.
WIZENABLEINFOWINDOW=1

:row.
:c.WIZENABLETOOLBAR
:c.1/0
:c.Enable or disable the toolbar of a folder.

:etable.










