.********** drag functions *********

.im drgCheckClass.inc

.im drgCheckIfFileSysOnly.inc

.im drgCheckSpecClass.inc

.im drgQueryNumObjects.inc



.********** menu functions *********

.im menucheckforitem.inc

.im menucheckitem.inc

.im menuenableitem.inc

.im menuinsertitem.inc

.im menuInsertSeparator.inc

.im menuQueryItemCount.inc

.im menuremoveitem.inc


.*********** window functions ********

.im winCreateWindow.inc

.im winfiledlg.inc

.im winObjectFromPRec.inc

.im winQueryContainerHWND.inc

.im winQueryContainerRecord.inc

.im winQueryContRecEmphasis.inc

.im winQueryFolderObjects.inc

.im winQueryObject.inc

.im winquerytext.inc

.im winQueryWindowPos.inc

.im winSettext.inc

.im winSetWindowPos.inc

.im winshowwindow.inc

.im winWindowFromID.inc



