:h2 res=400
width=30%
.Supported WPS methods
:p.
The following WPS methods are currently supported. These
are methods every OS/2 system supports. They are described in the
IBM WPS Programming reference.

:p.
.br
:link reftype=hd res=410 dependent.somGetClass:elink.
.br
:link reftype=hd res=420 dependent.somGetClassName:elink.
.br
:link reftype=hd res=430 dependent.somGetname:elink.
.br
:link reftype=hd res=440 dependent.somGetVersionNumbers:elink.
.br
:link reftype=hd res=450 dependent.wpClose:elink.
.br
:link reftype=hd res=820 dependent.wpCnrRefreshDetails:elink.
.br
:link reftype=hd res=810 dependent.wpCnrSetEmphasis:elink.
.br
:link reftype=hd res=780 dependent.wpCopyObject:elink.
.br
:link reftype=hd res=840 dependent.wpCreateFromTemplate:elink.
.br
:link reftype=hd res=790 dependent.wpCreateShadowObject:elink.
.br
:link reftype=hd res=740 dependent.wpDelete:elink.
.br
:link reftype=hd res=750 dependent.wpDeleteContents:elink.
.br
:link reftype=hd res=460 dependent.wpHide:elink.
.br
:link reftype=hd res=800 dependent.wpIsCurrentDesktop:elink.
.br
:link reftype=hd res=470 dependent.wpIsDeleteable:elink.
.br
:link reftype=hd res=760 dependent.wpIsLocked:elink.
.br
:link reftype=hd res=720 dependent.wpLockObject:elink.
.br
.*:link reftype=hd res=930 dependent.wpModifyStyle:elink.
wpModifyStyle
.br
:link reftype=hd res=770 dependent.wpMoveObject:elink.
.br
:link reftype=hd res=830 dependent.wpPopulate:elink.
.br
:link reftype=hd res=480 dependent.wpQueryAttr:elink.
.br
:link reftype=hd res=490 dependent.wpQueryConcurrentView:elink.
.br
:link reftype=hd res=500 dependent.wpQueryConfirmations:elink.
.br
:link reftype=hd res=510 dependent.wpQueryContent:elink.
.br
:link reftype=hd res=520 dependent.wpQueryDefaultView:elink.
.br
:link reftype=hd res=530 dependent.wpQueryDisk:elink.
.br
:link reftype=hd res=540 dependent.wpQueryEASize:elink.
.br
:link reftype=hd res=550 dependent.wpQueryFileSize:elink.
.br
:link reftype=hd res=900 dependent.wpQueryFldrDetailsClass:elink.
.br
:link reftype=hd res=560 dependent.wpQueryFldrFlags:elink.
.br
:link reftype=hd res=570 dependent.wpQueryFldrFont:elink.
.br
:link reftype=hd res=890 dependent.wpQueryFldrSortClass:elink.
.br
:link reftype=hd res=580 dependent.wpQueryFolder:elink.
.br
:link reftype=hd res=590 dependent.wpQueryHandle:elink.
.br
:link reftype=hd res=600 dependent.wpQueryObjectID:elink.
.br
:link reftype=hd res=610 dependent.wpQueryShadowedObject:elink.
.br
:link reftype=hd res=620 dependent.wpQueryStyle:elink.
.br
:link reftype=hd res=630 dependent.wpQueryTitle:elink.
.br
:link reftype=hd res=640 dependent.wpQueryType:elink.
.br
:link reftype=hd res=650 dependent.wpRefresh:elink.
.br
:link reftype=hd res=660 dependent.wpSaveDeferred:elink.
.br
:link reftype=hd res=670 dependent.wpSaveImmediate:elink.
.br
:link reftype=hd res=680 dependent.wpSetDefaultView:elink.
.br
:link reftype=hd res=910 dependent.wpSetFldrDetailsClass:elink.
.br
:link reftype=hd res=920 dependent.wpSetFldrSortClass:elink.
.br
:link reftype=hd res=690 dependent.wpSetLinkToObject:elink.
.br
:link reftype=hd res=870 dependent.wpSetObjectID:elink.
.br
:link reftype=hd res=700 dependent.wpSetStyle:elink.
.br
:link reftype=hd res=880 dependent.wpSetType:elink.
.br
:link reftype=hd res=860 dependent.wpSwitchTo:elink.
.br
:link reftype=hd res=730 dependent.wpUnlockObject:elink.
.br
:link reftype=hd res=850 dependent.wpViewObject:elink.
.br

.* Last res: 930


.* Description of the methods
.im sommethods.inc
.im wpmethoddesc.inc














