:h1.Source
:p.
The source is available here:
:p.
:lines align=center.
:link reftype=launch
object='netscape.exe'
data='http://www.geocities.com/SiliconValley/Sector/5785/index.html'.
http&colon.//www.geocities.com/SiliconValley/Sector/5785/index.html:elink.
:elines.

:note text='Note:'.
If you use any part of this distribution or the sources you :hp2.must:ehp2.
give the full source of your project to any user! There's no exception to
this rule. Read the licence section for more information.

:p.
If you need another licence drop me a note.
