:h1.Quelltext
:p.
Die Quelltexte sind unter folgendem URL erh„ltlich:
:p.
:lines align=center.
:link reftype=launch
object='netscape.exe'
data='http://www.geocities.com/SiliconValley/Sector/5785/index.html'.
http&colon.//www.geocities.com/SiliconValley/Sector/5785/index.html:elink.
:elines.

:note text='Hinweis:'.
Sollten irgendwelche Teile dieses Paketes oder der Quelltexte in eigenen Projekten
eingesetzt werden, so :hp2.mssen:ehp2. die vollst„ndigen Quelltexte des eigenen 
Projektes verfgbar gemacht werden! Die GPL l„át hier keine Ausnahmen zu. N„heres
im Abschnitt 'Lizenz'.

:p.
Sollte eine andere Lizenz gewnscht werden, dann eine Mail an mich.
